### ISSUE TITLE
Arabic

### ISSUE THREAD

**Issue by nhaouari** [obsidianmd/obsidian-translations#57]
Hi, 

Could you please add arabic template so I can work on it.

Thank you.

**Comment by ericaxu** [comment]
Arabic has the extra challenge of being RTL, which we need to support on the app level.

Do you think a text only version would help, when RTL is not ready?

**Comment by alaaio** [comment]
I will help working on the Arabic translation too. Even if it doesn't help it's a good start for the developers to know that there is interest from the Arabic speakers in their app. @ericaxu

**Comment by nhaouari** [comment]
> Arabic has the extra challenge of being RTL, which we need to support on the app level.
> 
> Do you think a text only version would help, when RTL is not ready?

It would help especially with some modification on obsidian.css to make the editor and menu appears right to left direction. I have tried these changes it gives very acceptable results: 
```css 
.app-container {
	direction: rtl !important;
}

.CodeMirror-code {
	direction: rtl !important;
}


.CodeMirror-sizer {
	margin-right: 18px !important;
	margin-left: auto !important;
        padding-left: 10px !important;
	padding-right: auto !important;
        border-left-width: 20px !important;
	border-right-width: auto !important;
}

.CodeMirror-gutter-wrapper .CodeMirror-gutter-elt .CodeMirror-gutter-wrapper {
	left:auto !important;
	right:0 !important;
}

```
